# Generated by Django 5.0.7 on 2024-07-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersreview',
            name='last_name',
        ),
    ]
