# Generated by Django 5.0.7 on 2024-07-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customersreview_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
